name: "table"
config:
  source: "urdf"
  urdf_path: "config/objects/table/table.urdf"
  publish_ground_truth: False
  base_position:
    - 0.0
    - 0.0
    - 0.0
  base_orientation: # x, y, z, w
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  global_scaling: 1