name: "ball"
config: 
  source: "primitive"
  publish_ground_truth: True
  visual: 
    shape_type: "GEOM_SPHERE"
    visual_shape: 
      radius: 0.05
      rgbaColor:
        - 0.0
        - 1.0
        - 0.0
        - 1.0
  collision:
    shape_type: "GEOM_SPHERE"
    collision_shape: 
      radius: 0.05
  multi_body: 
    baseMass: 0.1

  base_position: 
    - -0.5
    - 0.0
    - 0.5
  base_orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    

