name: "Cube"
config:
  source: "primitive"
  publish_ground_truth: False
  visual:
    shape_type: "GEOM_BOX"
    visual_shape:
      halfExtents:
      - 0.03
      - 0.015
      - 0.03
      rgbaColor:
      - 1.0
      - 0.0
      - 0.5
      - 1.0
  collision:
    shape_type: "GEOM_BOX"
    collision_shape:
      halfExtents:
      - 0.03
      - 0.015
      - 0.03
  multi_body:
    baseMass: 2

  base_position:
  - 0.0
  - -0.2
  - 0.7
  base_orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
