name: "power_drill"
config:
  source: "urdf"
  urdf_path: "config/objects/power_drill/model.urdf"
  publish_ground_truth: False
  base_position:
  - -0.5
  - 0.5
  - 0.3
  base_orientation:
  # x, y, z, w
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  global_scaling: 1.5
