name: "floor"
config: 
  source: "primitive"
  publish_ground_truth: False
  visual: 
    shape_type: "GEOM_BOX"
    visual_shape: 
      halfExtents: 
        - 1
        - 1
        - 0.1
      rgbaColor:
        - 1.0
        - 0.0
        - 0.5
        - 1.0
  collision:
    shape_type: "GEOM_BOX"
    collision_shape:
      halfExtents: 
        - 1
        - 1
        - 0.1
  multi_body: 
    baseMass: 0

  base_position: 
    - 0.0
    - 0.0
    - 0.0
  base_orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0

